service: cortrie
useDotenv: true

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: '200m'
      heapMax: '1g'
      migrate: true
      seed: true
      convertEmptyValues: true
  optimize:
    external: ['swagger-ui-dist']
    externalPaths:
      swagger-ui-dist: 'node_modules/swagger-ui-dist'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{any+}'
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin
